(()=>{const windowEl=document.querySelector('.scripture-window');if(!windowEl)return;
const passages=[['Orai sem cessar.','1 Tessalonicenses 5:17'],['Deus é amor.','1 João 4:8'],['O Senhor é o meu pastor; nada me faltará.','Salmos 23:1'],['Não temas, porque eu sou contigo.','Isaías 41:10'],['Tudo posso naquele que me fortalece.','Filipenses 4:13'],['O Senhor é a minha luz e a minha salvação.','Salmos 27:1'],['Alegrai-vos sempre no Senhor.','Filipenses 4:4'],['Em tudo dai graças.','1 Tessalonicenses 5:18'],['Bem-aventurados os pacificadores.','Mateus 5:9'],['Se Deus é por nós, quem será contra nós?','Romanos 8:31'],['Aquietai-vos e sabei que eu sou Deus.','Salmos 46:10'],['O meu socorro vem do Senhor.','Salmos 121:2'],['Confia no Senhor de todo o teu coração.','Provérbios 3:5'],['A minha graça te basta.','2 Coríntios 12:9'],['O Senhor te abençoe e te guarde.','Números 6:24']];
const verse=windowEl.querySelector('.scripture-verse'),ref=windowEl.querySelector('.scripture-reference'),content=windowEl.querySelector('.scripture-content'),control=windowEl.querySelector('button');let current=-1,paused=false,timer,fadeTimer;
function fit(){verse.style.fontSize='18px';const available=verse.clientWidth;if(available>0&&verse.scrollWidth>available)verse.style.fontSize=(18*available/verse.scrollWidth)+'px';}
function pick(){let next=Math.floor(Math.random()*passages.length);if(next===current)next=(next+1+Math.floor(Math.random()*(passages.length-1)))%passages.length;current=next;verse.textContent='“'+passages[current][0]+'”';ref.textContent=passages[current][1];fit();}
function schedule(){clearTimeout(timer);if(!paused&&!document.hidden)timer=setTimeout(()=>{content.classList.add('fading');fadeTimer=setTimeout(()=>{pick();content.classList.remove('fading');schedule();},280);},2720+Math.random()*2000);}
function stop(){clearTimeout(timer);clearTimeout(fadeTimer);content.classList.remove('fading');}
control.addEventListener('click',()=>{paused=!paused;control.setAttribute('aria-pressed',String(paused));control.setAttribute('aria-label',paused?'Retomar passagens bíblicas':'Pausar passagens bíblicas');control.textContent=paused?'▶':'Ⅱ';stop();schedule();});
document.addEventListener('visibilitychange',()=>{stop();schedule();});window.addEventListener('resize',fit);if(document.fonts)document.fonts.ready.then(fit);pick();schedule();})();
